[package]
name = "rust-testpkg"
version = "0.1.0"
authors = ["Joe Hendrix <jhendrix@galois.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
